
import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { getCurrentLang, getLangString } from '@/services/languageService';

const FAQ = () => {
  const currentLang = getCurrentLang();

  const faqs = [
    {
      question: currentLang === 'en-US' ? 'Which languages does the tool support?' :
                currentLang === 'es-ES' ? '¿Qué idiomas admite la herramienta?' :
                'Quais idiomas a ferramenta suporta?',
      answer: currentLang === 'en-US' ? 'Our system automatically detects the language of the YouTube video using the available captions. If the video has no subtitles, we default to English, but the AI chat will always answer in the language you speak to it. You can upload a video in Chinese and talk to the AI in English, Spanish, Portuguese — anything.' :
              currentLang === 'es-ES' ? 'Nuestro sistema detecta automáticamente el idioma del video de YouTube usando los subtítulos disponibles. Si el video no tiene subtítulos, usamos inglés por defecto, pero el chat de IA siempre responderá en el idioma que le hables. Puedes subir un video en chino y hablar con la IA en inglés, español, portugués — lo que sea.' :
              'Nosso sistema detecta automaticamente o idioma do vídeo do YouTube usando as legendas disponíveis. Se o vídeo não tiver legendas, usamos inglês por padrão, mas o chat de IA sempre responderá no idioma que você falar com ele. Você pode enviar um vídeo em chinês e falar com a IA em inglês, espanhol, português — qualquer coisa.'
    },
    {
      question: currentLang === 'en-US' ? 'Is there a limit to the video duration?' :
                currentLang === 'es-ES' ? '¿Hay un límite para la duración del video?' :
                'Existe um limite para a duração do vídeo?',
      answer: currentLang === 'en-US' ? 'No duration limit! Your plan uses credits, and 1 credit = 1 video transcription, no matter how long it is. Only playlists behave differently: Each video in a playlist counts as one credit. Adding a playlist will transcribe all videos inside it and deduct credits accordingly (So be careful with very large playlists!)' :
              currentLang === 'es-ES' ? '¡Sin límite de duración! Tu plan usa créditos, y 1 crédito = 1 transcripción de video, sin importar cuán largo sea. Solo las listas de reproducción se comportan diferente: Cada video en una lista cuenta como un crédito. Agregar una lista transcribirá todos los videos dentro y deducirá créditos en consecuencia (¡Ten cuidado con listas muy grandes!)' :
              'Sem limite de duração! Seu plano usa créditos, e 1 crédito = 1 transcrição de vídeo, não importa quão longo seja. Apenas playlists se comportam de forma diferente: Cada vídeo em uma playlist conta como um crédito. Adicionar uma playlist transcreverá todos os vídeos dentro dela e deduzirá créditos de acordo (Então tenha cuidado com playlists muito grandes!)'
    },
    {
      question: currentLang === 'en-US' ? 'Is the platform mobile-friendly?' :
                currentLang === 'es-ES' ? '¿La plataforma es compatible con móviles?' :
                'A plataforma é compatível com dispositivos móveis?',
      answer: currentLang === 'en-US' ? 'Yes! You can use the entire tool on your phone or tablet without any issues.' :
              currentLang === 'es-ES' ? '¡Sí! Puedes usar toda la herramienta en tu teléfono o tableta sin ningún problema.' :
              'Sim! Você pode usar toda a ferramenta no seu telefone ou tablet sem problemas.'
    },
    {
      question: currentLang === 'en-US' ? 'Are the summaries generated by AI?' :
                currentLang === 'es-ES' ? '¿Los resúmenes son generados por IA?' :
                'Os resumos são gerados por IA?',
      answer: currentLang === 'en-US' ? 'Yes — summaries are created by our AI model. The full transcript, however, comes directly from YouTube captions (original or auto-generated).' :
              currentLang === 'es-ES' ? 'Sí — los resúmenes son creados por nuestro modelo de IA. La transcripción completa, sin embargo, proviene directamente de los subtítulos de YouTube (originales o generados automáticamente).' :
              'Sim — resumos são criados pelo nosso modelo de IA. A transcrição completa, no entanto, vem diretamente das legendas do YouTube (originais ou geradas automaticamente).'
    },
    {
      question: currentLang === 'en-US' ? 'Can I save or review my past summaries?' :
                currentLang === 'es-ES' ? '¿Puedo guardar o revisar mis resúmenes anteriores?' :
                'Posso salvar ou revisar meus resumos anteriores?',
      answer: currentLang === 'en-US' ? 'Absolutely. All summaries and transcripts are stored in your dashboard so you can revisit them anytime.' :
              currentLang === 'es-ES' ? 'Absolutamente. Todos los resúmenes y transcripciones se almacenan en tu panel para que puedas revisarlos en cualquier momento.' :
              'Absolutamente. Todos os resumos e transcrições são armazenados no seu painel para que você possa revisitá-los a qualquer momento.'
    },
    {
      question: currentLang === 'en-US' ? 'How many videos can I transcribe?' :
                currentLang === 'es-ES' ? '¿Cuántos videos puedo transcribir?' :
                'Quantos vídeos posso transcrever?',
      answer: currentLang === 'en-US' ? 'As many as your plan allows. Each transcription uses 1 credit, regardless of video length.' :
              currentLang === 'es-ES' ? 'Tantos como tu plan lo permita. Cada transcripción usa 1 crédito, independientemente de la duración del video.' :
              'Quantos seu plano permitir. Cada transcrição usa 1 crédito, independentemente da duração do vídeo.'
    },
    {
      question: currentLang === 'en-US' ? 'Does it work with private or unlisted videos?' :
                currentLang === 'es-ES' ? '¿Funciona con videos privados o no listados?' :
                'Funciona com vídeos privados ou não listados?',
      answer: currentLang === 'en-US' ? 'At the moment, we only support public YouTube videos. Private or unlisted videos cannot be processed.' :
              currentLang === 'es-ES' ? 'Por el momento, solo admitimos videos públicos de YouTube. Los videos privados o no listados no se pueden procesar.' :
              'No momento, suportamos apenas vídeos públicos do YouTube. Vídeos privados ou não listados não podem ser processados.'
    }
  ];

  return (
    <section id="faq" className="section-padding bg-accent/10">
      <div className="container-width">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            <span className="gradient-text">{getLangString('faqTitle', currentLang)}</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            {getLangString('faqSubtitle', currentLang)}
          </p>
        </div>

        <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm border border-border/50 overflow-hidden">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="px-6 py-4 hover:bg-accent/20 transition-colors text-left font-medium">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="px-6 py-4 text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
