// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upheowtfrqmyipyqkmbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaGVvd3RmcnFteWlweXFrbWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTg2NTYsImV4cCI6MjA2MjM3NDY1Nn0.hM0YkJ_AoBZI1WoeLJ6-FPU0xhER70OINJq9TFNLu70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);